//Generated by JSONToObjectiveC on Jul 24, 2014, 2:10:50 PM

#import <Mantle/Mantle.h>

@interface DSCheckboxTab : MTLModel <MTLJSONSerializing>

@property (nonatomic, strong) NSString *anchorIgnoreIfNotPresent;
@property (nonatomic, strong) NSString *anchorString;
@property (nonatomic, strong) NSString *anchorUnits;
@property (nonatomic, strong) NSNumber *anchorXOffset;
@property (nonatomic, strong) NSNumber *anchorYOffset;
@property (nonatomic, strong) NSString *conditionalParentLabel;
@property (nonatomic, strong) NSString *conditionalParentValue;
@property (nonatomic, strong) NSString *documentId;
@property (nonatomic, strong) NSString *locked;
@property (nonatomic, strong) NSString *mergeFieldXml;
@property (nonatomic, strong) NSString *name;
@property (nonatomic, strong) NSNumber *pageNumber;
@property (nonatomic, strong) NSString *recipientId;
@property (nonatomic, strong) NSString *required;
@property (nonatomic, strong) NSString *requireInitialOnSharedChange;
@property (nonatomic, strong) NSString *selected;
@property (nonatomic, strong) NSString *shared;
@property (nonatomic, strong) NSString *tabId;
@property (nonatomic, strong) NSString *tabLabel;
@property (nonatomic, strong) NSNumber *xPosition;
@property (nonatomic, strong) NSNumber *yPosition;

@end