//Generated by JSONToObjectiveC on Jul 24, 2014, 2:10:50 PM

#import <Mantle/Mantle.h>

@interface DSLastNameTab : MTLModel <MTLJSONSerializing>

@property (nonatomic, strong) NSString *anchorIgnoreIfNotPresent;
@property (nonatomic, strong) NSString *anchorString;
@property (nonatomic, strong) NSString *anchorUnits;
@property (nonatomic, strong) NSNumber *anchorXOffset;
@property (nonatomic, strong) NSNumber *anchorYOffset;
@property (nonatomic, strong) NSString *bold;
@property (nonatomic, strong) NSString *conditionalParentLabel;
@property (nonatomic, strong) NSString *conditionalParentValue;
@property (nonatomic, strong) NSString *documentId;
@property (nonatomic, strong) NSString *font;
@property (nonatomic, strong) NSString *fontColor;
@property (nonatomic, strong) NSNumber *fontSize;
@property (nonatomic, strong) NSString *italic;
@property (nonatomic, strong) NSString *name;
@property (nonatomic, strong) NSNumber *pageNumber;
@property (nonatomic, strong) NSString *recipientId;
@property (nonatomic, strong) NSString *tabId;
@property (nonatomic, strong) NSString *tabLabel;
@property (nonatomic, strong) NSString *underline;
@property (nonatomic, strong) NSNumber *xPosition;
@property (nonatomic, strong) NSNumber *yPosition;

@end