//Generated by JSONToObjectiveC on Jul 24, 2014, 2:10:50 PM

#import "DSListTab.h"
#import "DSListItem.h"

@implementation DSListTab

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    return nil;
}

+ (NSValueTransformer *)listItemsJSONTransformer {
    return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[DSListItem class]];
}

@end