//Generated by JSONToObjectiveC on Jul 24, 2014, 2:10:50 PM

#import <Mantle/Mantle.h>

@interface DSListItem : MTLModel <MTLJSONSerializing>

@property (nonatomic, strong) NSString *selected;
@property (nonatomic, strong) NSString *text;
@property (nonatomic, strong) NSString *value;

@end