//Generated by JSONToObjectiveC on Jul 24, 2014, 2:10:50 PM

#import "DSRadioGroupTab.h"
#import "DSRadio.h"

@implementation DSRadioGroupTab

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    return nil;
}

+ (NSValueTransformer *)radiosJSONTransformer {
    return [NSValueTransformer mtl_JSONArrayTransformerWithModelClass:[DSRadio class]];
}

@end