//Generated by JSONToObjectiveC on Jul 24, 2014, 2:10:50 PM

#import "DSRadioGroupTab.h"

@implementation DSRadioGroupTab

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    return nil;
}
// TODO transform array

@end