//Generated by JSONToObjectiveC on Jul 24, 2014, 2:10:50 PM

#import <Mantle/Mantle.h>

@interface DSRadio : MTLModel <MTLJSONSerializing>

@property (nonatomic, strong) NSString *anchorIgnoreIfNotPresent;
@property (nonatomic, strong) NSString *anchorString;
@property (nonatomic, strong) NSString *anchorUnits;
@property (nonatomic, strong) NSNumber *anchorXOffset;
@property (nonatomic, strong) NSNumber *anchorYOffset;
@property (nonatomic, strong) NSString *locked;
@property (nonatomic, strong) NSNumber *pageNumber;
@property (nonatomic, strong) NSString *required;
@property (nonatomic, strong) NSString *selected;
@property (nonatomic, strong) NSString *tabId;
@property (nonatomic, strong) NSString *value;
@property (nonatomic, strong) NSNumber *xPosition;
@property (nonatomic, strong) NSNumber *yPosition;

@end