//Generated by JSONToObjectiveC on Jul 24, 2014, 2:10:50 PM

#import <Mantle/Mantle.h>

@interface DSRadioGroupTab : MTLModel <MTLJSONSerializing>

@property (nonatomic, strong) NSString *conditionalParentLabel;
@property (nonatomic, strong) NSString *conditionalParentValue;
@property (nonatomic, strong) NSString *documentId;
@property (nonatomic, strong) NSString *groupName;
@property (nonatomic, strong) NSArray  *radios;
@property (nonatomic, strong) NSString *recipientId;
@property (nonatomic, strong) NSString *requireInitialOnSharedChange;
@property (nonatomic, strong) NSString *shared;

@end