//Generated by JSONToObjectiveC on Jul 24, 2014, 2:10:50 PM

#import "DSSignerAttachmentTab.h"

@implementation DSSignerAttachmentTab

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    return nil;
}

@end