//Generated by JSONToObjectiveC on Jul 24, 2014, 2:10:50 PM

#import <Mantle/Mantle.h>

@interface DSTabs : MTLModel <MTLJSONSerializing>

@property (nonatomic, strong) NSArray  *approveTabs;
@property (nonatomic, strong) NSArray  *checkboxTabs;
@property (nonatomic, strong) NSArray  *companyTabs;
@property (nonatomic, strong) NSArray  *dateSignedTabs;
@property (nonatomic, strong) NSArray  *dateTabs;
@property (nonatomic, strong) NSArray  *declineTabs;
@property (nonatomic, strong) NSArray  *emailAddressTabs;
@property (nonatomic, strong) NSArray  *emailTabs;
@property (nonatomic, strong) NSArray  *envelopeIdTabs;
@property (nonatomic, strong) NSArray  *firstNameTabs;
@property (nonatomic, strong) NSArray  *formulaTabs;
@property (nonatomic, strong) NSArray  *fullNameTabs;
@property (nonatomic, strong) NSArray  *initialHereTabs;
@property (nonatomic, strong) NSArray  *lastNameTabs;
@property (nonatomic, strong) NSArray  *listTabs;
@property (nonatomic, strong) NSArray  *noteTabs;
@property (nonatomic, strong) NSArray  *numberTabs;
@property (nonatomic, strong) NSArray  *radioGroupTabs;
@property (nonatomic, strong) NSArray  *signerAttachmentTabs;
@property (nonatomic, strong) NSArray  *signHereTabs;
@property (nonatomic, strong) NSArray  *ssnTabs;
@property (nonatomic, strong) NSArray  *textTabs;
@property (nonatomic, strong) NSArray  *titleTabs;
@property (nonatomic, strong) NSArray  *zipTabs;

@end