//Generated by JSONToObjectiveC on Jul 24, 2014, 2:10:50 PM

#import "DSTabs.h"
#import "DSApproveTab.h"
#import "DSCheckboxTab.h"
#import "DSCompanyTab.h"
#import "DSDateSignedTab.h"
#import "DSDateTab.h"
#import "DSDeclineTab.h"
#import "DSEmailAddressTab.h"
#import "DSEmailTab.h"
#import "DSEnvelopeIdTab.h"
#import "DSFirstNameTab.h"
#import "DSFormulaTab.h"
#import "DSFullNameTab.h"
#import "DSInitialHereTab.h"
#import "DSLastNameTab.h"
#import "DSListTab.h"
#import "DSNoteTab.h"
#import "DSNumberTab.h"
#import "DSRadioGroupTab.h"
#import "DSSignerAttachmentTab.h"
#import "DSSignHereTab.h"
#import "DSSsnTab.h"
#import "DSTextTab.h"
#import "DSTitleTab.h"
#import "DSZipTab.h"

@implementation DSTabs

+ (NSDictionary *)JSONKeyPathsByPropertyKey {
    return nil;
}

@end